### ISSUE TITLE
compilation fails under Ubuntu 16.04

### ISSUE THREAD

**Issue by hadmut** [pepabo/imlib2-ruby#2]
Compilation fails with 
imlib2.c: In function ‘raise_imlib_error’:
imlib2.c:166:41: error: format not a string literal and no format arguments [-Werror=format-security]
   rb_raise(imlib_errors[err].exception, buf);
                                         ^
cc1: some warnings being treated as errors

**Comment by hfm** [comment]
@hadmut I'll fix this problem by #3. Thank you.
